package edu.upenn.cit5940.datamanagement;

//WE CAN EXTRACT SOME PARTS OF THIS SO WE CAN HAVE A CSV PARSE, JSON, AND TXT FILE BUT FOR NOW LET'S DO THEM SEPARATE AN DSEE HWERE WE CANC CONDENSE
public class FileReader {
}